exports.periodocompListPage = function(compList, d){
    console.log(compList.length)
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de períodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h3 class = "w3-left w3-margin-left w3-allerta w3-button w3-white w3-round-large">
                    <a href="http://localhost:3050">Compositores</a>
                    <h1 class = "w3-center">Lista de Periódos
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th>
                        </tr>
                `
    for(let i=0; i < compList.length ; i++){
        pagHTML += `
                <tr>
                    <td>${compList[i].id}</td>
                    <td>
                        <a href="/periodos/${compList[i].id}">
                            ${compList[i].nome}
                        </a>
                    </td>

                    <td>
                        [<a href="/periodos/edit/${compList[i].id}">Edit</a>][<a href="/periodos/delete/${compList[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}




exports.compositorcompListPage = function(listaPeriodos,compList, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores de Musica</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h3 class = "w3-left w3-margin-left w3-allerta w3-button w3-white w3-round-large">
                    <a href="http://localhost:3050/periodos">Períodos</a>
                    <h1 class="w3-center">Lista de Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th>
                            <th>Periodo</th>
                        </tr>
                `
    for(let i=0; i < compList.length ; i++){
        pagHTML += `
                <tr>
                    <td>${compList[i].id}</td>
                    <td>
                        <a href="/compositores/${compList[i].id}">
                            ${compList[i].nome}
                        </a>
                    </td>
                    <td>
                        <a href="/periodos/${compList[i].periodo}">
                            ${listaPeriodos[compList[i].periodo]}
                        </a>
                    </td>

                    <td>
                        [<a href="/compositores/edit/${compList[i].id}">Edit</a>][<a href="/compositores/delete/${compList[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoFormPage = function(d){
    return`
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Period Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>

                
    
    `
}

exports.periodoFormEditPage = function(d,periodo){
    return`
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" "type="text" name="id" value="${periodo.id}" required readonly/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${periodo.nome}" required/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>

                
    
    `
}

exports.compositorFormPage = function(listaPeriodos,d){
    pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" required/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" required/>
                        <label for="periodos">Período:</label>
                        <select class="w3-select" id="periodos" name="periodo" required>
                            <option value="" disabled selected>Choose your Period</option>
    `


    for (i = 0; i<listaPeriodos.length;i++)
        pagHTML += `        <option value="${listaPeriodos[i].id}">${listaPeriodos[i].nome}</option>`

    pagHTML += 
    `                   </select>
                    </fieldset>
                    <fieldset>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" required/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.compositorEditPage = function(listaPeriodos,compositor,periodoAtual,d){


    pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" value ="${compositor.id}" readonly/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value ="${compositor.nome}"required/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value ="${compositor.dataNasc}" required/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value ="${compositor.dataObito}" required/>
                        <label for="periodos">Período:</label>
                        <select class="w3-select" id="periodos" name="periodo" required>
                            <option  value ="${compositor.periodo}">${periodoAtual}</option>
    `


    for (i = 0; i<listaPeriodos.length;i++){
        if (listaPeriodos[i].id != compositor.periodo)
            pagHTML += `        <option value="${listaPeriodos[i].id}">${listaPeriodos[i].nome}</option>`
    }
    pagHTML += 
    `                   </select>
                    </fieldset>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${compositor.bio}" required/>
                    <fieldser>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>
                <footer class="w3-container w3-teal">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Compositor's Page--------------------------------
exports.compositorPage = function(compositor, nomePeriodo, d ){

    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${compositor.dataObito}</li
                    <li><b>Período (link): </b> <a href="/periodos/${compositor.periodo}">${nomePeriodo}</a></li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <h2>Biografia</h2>
                <p>${compositor.bio}</p>
            </div>
            `

    

    pagHTML +=     `</ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}



// ---------------Period's Page--------------------------------
exports.periodoPage = function(compList, periodo, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${periodo.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>${periodo.nome}</h1>
            </header>
            <div class="w3-container">
            <h1>Compositores</h1>
            <table class="w3-table-all">
                <tr>
                    <th>Id</th><th>Nome</th>
                </tr>
            `
    for(let i=0; i < compList.length ; i++){
    pagHTML += `
            <tr>
                <td>${compList[i].id}</td>
                <td>
                    <a href="/compositores/${compList[i].id}">
                        ${compList[i].nome}
                    </a>
                </td>
                <td>
                    [<a href="/compositores/edit/${compList[i].id}">Edit</a>][<a href="/compositores/delete/${compList[i].id}">Delete</a>]
                </td>
            </tr>
    `
    }

    pagHTML += `
        </table>
        </div>
            <footer class="w3-container w3-teal">
                <h5>Generated by RPCW2023 in ${d}</h5>
            </footer>
        </div>
    </body>
    </html>
    `

    


    return pagHTML
}


// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}